openapi: 3.0.0
info:
  title: DocFlow API
  version: 0.1.9

paths:
  /document/{documentId}:
    get:
      tags:
        - Document
      description: "Returns a document"
      parameters:
        - name: "documentId"
          in: "path"
          required: true
          schema:
            $ref: '#/components/schemas/DocumentId'
      responses:
        '204':
          $ref: '#/components/responses/NoContent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    DocumentId:
      description: "ID of the document to return"
      type: string

  responses:
    NoContent:
      description: Operation successfully completed
    BadRequest:
      description: Invalid user request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    NotFound:
      description: Object not found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
