AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  docflow

  Application for managing tickets with messages

Globals:
  Function:
    Runtime: python3.8
    Timeout: 30
    Handler: index.handler

Resources:
  CreateDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/CreateDocument
      Description: Allows for issuing presigned links to create new documents
      Events:
        CreateDocument:
          Type: Api
          Properties:
            Path: /documents
            Method: post
  GetDocumentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/GetDocuments
      Description: Allows for issuing presigned links to create new documents
      Events:
        GetDocument:
          Type: Api
          Properties:
            Path: /documents
            Method: get

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint for the API functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
